includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/BOIL.yaml
  - backbones/resnet12.yaml

# This config can reach
# (66.629+-0.308) (NIL test)
# reported 66.45 ± 0.37

way_num: 5
shot_num: 5
query_num: 15
data_root: /data/wzy/miniImageNet--ravi
image_size: 84
use_memory: False
augment: False
augment_times: 1
augment_times_query: 1
episode_size: 4
train_episode: 1000
test_episode: 50
# actually BOIL uses idiot_train (train without validation, then test)
skip_val_epochs: 200
# so we add a skip_val_epochs(idiot_train) option
epoch: 200
device_ids: 1
n_gpu: 1


optimizer:
  name: Adam
  kwargs:
    lr: 6e-4
  other:
    emb_func: 6e-4

lr_scheduler:
  name: StepLR
  kwargs:
    gamma: 1.0
    step_size: 10


classifier:
  name: BOIL
  kwargs:
    inner_param:
      classifier_lr: 0.0
      extractor_lr: 0.3
    feat_dim: 640
    testing_method: NIL

backbone:
  name: resnet12
  kwargs:
    keep_prob: 0.0
    avg_pool: True
    is_flatten: True
    maxpool_last2: True
